### ISSUE TITLE
TypeError in Firefox when loading CCM

### ISSUE THREAD

**Issue by minhnh** [ccmjs/ccm#2]
* The same loading procedure works fine in Vivaldi (Chromium based)
* Firefox version: 64.0.2

![screenshot](https://user-images.githubusercontent.com/1168534/51476837-fb45f580-1d86-11e9-88bd-19b8b0d51efd.png)

Edit: I have seen this deprecation message for a while in Vivaldi, maybe it's relevant?

![screenshot](https://user-images.githubusercontent.com/1168534/51477311-604e1b00-1d88-11e9-8421-6f21f547d7ec.png)

**Comment by akless** [comment]
In which situation does the error occur exactly? When loading a HTML file via ccm.load? If that's the case, it's because HTML Import in Firefox does not work. The HTML import is already obsolete anyway and will soon no longer be supported by _ccm_.

An HTML file can also be loaded via ccm.load like this:
`ccm.load( { url: 'path/to/my.html', type: 'data' } )`
The result is then the contents of the HTML file as a string.

**Comment by minhnh** [comment]
Ok, then I guess I should avoid loading HTML file like this from now on. Closing issue.
